import { Github, Linkedin, Twitter, Youtube } from "lucide-react";

export const FOOTER_LINKS = {
  products: [
    { name: "AI", href: "#" },
    { name: "Enterprise", href: "#" },
    { name: "Fluid Compute", href: "#" },
    { name: "Next.js", href: "#", external: true },
    { name: "Observability", href: "#" },
    { name: "Previews", href: "#" },
    { name: "Rendering", href: "#" },
    { name: "Security", href: "#" },
    { name: "Turbo", href: "#" },
    { name: "v0", href: "#", external: true },
  ],
  resources: [
    { name: "Community", href: "#", external: true },
    { name: "Docs", href: "#" },
    { name: "Guides", href: "#" },
    { name: "Help", href: "#" },
    { name: "Integrations", href: "#" },
    { name: "Pricing", href: "#" },
    { name: "Resources", href: "#" },
    { name: "Solution Partners", href: "#" },
    { name: "Templates", href: "#" },
  ],
  company: [
    { name: "About", href: "#" },
    { name: "Blog", href: "#" },
    { name: "Careers", href: "#" },
    { name: "Changelog", href: "#" },
    { name: "Contact Us", href: "#" },
    { name: "Customers", href: "#" },
    { name: "Partners", href: "#" },
    { name: "Privacy Policy", href: "#" },
    {
      name: "Legal",
      dropdown: true,
      subItems: [
        { name: "Cookie Policy", href: "#/legal/cookie-policy" },
        { name: "Cookie Preferences", href: "#/legal/cookie-preferences" },
        { name: "DMCA Policy", href: "#/legal/dmca-policy" },
        { name: "DORA Addendum", href: "#/legal/dora-addendum" },
        { name: "DPA", href: "#/legal/dpa" },
        { name: "DRA", href: "#/legal/dra" },
        {
          name: "Event Code of Conduct",
          href: "#/legal/event-code-of-conduct",
        },
        { name: "Event Terms and Conditions", href: "#/legal/event-terms" },
        { name: "Inactivity Policy", href: "#/legal/inactivity-policy" },
        { name: "Job Applicant Privacy Notice", href: "#/legal/job-privacy" },
        { name: "Privacy Policy", href: "#/legal/privacy" },
        { name: "SLA", href: "#/legal/sla" },
        { name: "Sub-processors", href: "#/legal/sub-processors" },
        { name: "Support Terms", href: "#/legal/support-terms" },
        { name: "Terms of Service", href: "#/legal/terms" },
        { name: "Trademark Policy", href: "#/legal/trademark" },
      ],
    },
  ],
  social: [
    { name: "GitHub", href: "#", icon: Github },
    { name: "LinkedIn", href: "#", icon: Linkedin },
    { name: "Twitter", href: "#", icon: Twitter },
    { name: "YouTube", href: "#", icon: Youtube },
  ],
};
